### PR TITLE
Add support for BrowserSync callback

### PR DESCRIPTION
**Pull request by danielcrisp**
[BrowserSync offers a callback option](https://www.browsersync.io/docs/api/#api-init) that is called when the setup is complete.

It includes a reference to the BrowserSync instance, which is useful to have access to for performing other tasks outside metalsmith

### CODE REVIEW

**Comment by mdvorscak** [comment]
Looks great, but could you add unit tests for the new functionality?

**Comment by danielcrisp** [comment]
Oops, didn't spot the tests sorry. 

Added a simple test - how's that?

**Comment by mdvorscak** [comment]
Great, thanks!

**Comment by danielcrisp** [comment]
Thank you - could you add a new `tag` so I can get the latest version from npm please?

**Comment by mdvorscak** [comment]
Sorry for the delay, it's been updated now.

**Pull request merged**
